use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :hw06, Hw06Web.Endpoint,
  server: true,
  root: ".",
  version: Application.spec(:phoenix_distillery, :vsn),
  http: [:inet6, port: {:system, "PORT"}],
  url: [host: "hw06.ericgift.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info


get_secret = fn name ->
  base = Path.expand("~/.config/hw06")
  File.mkdir_p!(base)
  path = Path.join(base, name)
  unless File.exists?(path) do
    secret = Base.encode16(:crypto.strong_rand_bytes(32))
    File.write!(path, secret)
  end
  File.read!(path)
end

config :hw06, Hw06Web.Endpoint,
  secret_key_base: get_secret.("key_base");

# Configure your database
config :hw06, Hw06.Repo,
  username: "hw06",
  password: get_secret.("db_pass"),
  database: "hw06_prod",
  pool_size: 15
